version: "3.1"

services:
  rasa:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    depends_on:
      - action-server

  action-server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
